<table id="tableAluno" class="display" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>RG</th>
            <th>Data Nasc.</th>
            <th>Curso</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <!--<th>ID</th>
            <th>Nome</th>
            <th>RG</th>
            <th>Data Nasc.</th>
            <th>Curso</th>-->
        </tr>
    </tfoot>
</table>