<strong>Cadastro de Disciplina</strong>
<p>Preencha os campos abaixo.</p>
<table id="cadastrarDisciplina" cellspacing="0">
    <thead>
    <form action="<?php echo basePath; ?>/disciplina/salvar" method="post">
        <tr class="nomeDisciplina">
            <td>Nome Disciplina:</td>
            <td><input type="text" name="nomeDisciplina" maxlength="45" id="nomeDisciplina" value=""></td>
            <td>*</td>
        </tr>
        <tr class="nomeProfessor">
            <td>Nome Professor:</td>
            <td><input type="text" name="nomeProfessor" maxlength="12" id="nomeProfessor" value=""></td>
            <td>*</td>
        </tr>
        <tr class="dataInicio">
            <td>Data Inicio:</td>
            <td><input type="text" name="dataInicio" id="dataInicio" value=""></td>
            <td>*</td>
        </tr>
        <tr class="nomeCurso">
            <td>Nome do Curso:</td>
            <td><input type="text" name="nomeCurso" maxlength="45" id="nomeCurso" value=""></td>
            <td>*</td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" id="salvarDisciplina" value="Salvar"></td>
            <td></td>
        </tr>
    </form>
    </thead>
</table>
<?php
    if($data['type'] == 'ERROR')
        echo '<span id="msg" style="color:red">'.$data['data'].'</span>';
    else
        echo '<span id="msg" style="color:green">'.$data['data'].'</span>';
?>