<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <link rel="stylesheet" type="text/css" href="/public/css/estilo.css">
        <script src="/public/js/jquery-3.1.1.min.js"></script>
        <script src="/public/js/functions.js"></script>

        <title>Projeto de Sistemas Web</title>
    </head>

    <body>
        <div class="principal">
            <div class="cabecalho">
                <div class="logo-cabecalho"></div>
            </div>
            <div class="menu">
                <ul>
                    <li> <a href="/">Início</a></li>
                    <li> <a href="/service/teste" id="teste">Teste</a></li>
                </ul>
            </div>
            <div class="corpo">
                <div class="conteudo">
                    <br />
                    <div id="retorno">Bem-Vindo!</div>
                    <br /><br />
                </div>
            </div>
            <div class="rodape">
                EAD IFMG | Projeto de Sistemas Web | 2017
            </div>
        </div>
    </body>
</html>