<table id="listarTurma" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Cod</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <!--<th>ID</th>
            <th>Nome</th>
            <th>Cod</th>-->
        </tr>
    </tfoot>
</table>

<script type="text/javascript">
    $('#listarTurma').DataTable( {
        data: <?php echo $data; ?>,
        columns: [
            { data: 'idcadastroTurma' },
            { data: 'nome' },
            { data: 'cod' },
            { data: 'idcadastroTurma' },
        ],
        "columnDefs": [ {
            "targets": 3,
            "render": function (data, type, full, meta ) {
              return '<a href="<?php echo basePath; ?>/turma/excluir/'+data+'">Excluir</a>';
            }
          } ]
    });
</script>